language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key: 
    secure: <YOUR ENCRYPTED KEY HERE>
  app: motivATR
  on:
    repo: git@github.com:dterrones4/MotivATR.git
